require 'echoe'
require 'rake/hooks'
require 'rake/clean'

CLOBBER.include 'models'

VERSION = File.read('VERSION').strip
RAILS_PATH = File.join('..', 'cveprovider')

Echoe.new('fidius-cve-template', VERSION) do |p|
  p.summary     = 'Foo'
  p.description = 'Bar'
  p.url         = 'http://fidius.me'
  p.author      = 'Fidius'
  p.email       = 'grp-fidius@tzi.org'
  p.runtime_dependencies = ['rails']
end

before :build do
  copy_files
end

after :package do
  version_increment
end

def version_increment
  v= VERSION.split('.')
  v[2] = v[2].to_i + 1
  File.open('VERSION', 'w') do |f|
    f.write(v.join('.'))
  end
end

def copy_files
  FileUtils.cp_r(File.expand_path(File.join(RAILS_PATH, 'app', 'models')),
               File.expand_path(File.dirname(__FILE__)))
end