require 'echoe'
require 'rake/hooks'
require 'rake/clean'

CLOBBER.include 'models', 'cveparser', 'migrate', 'tasks'

CVE_VERSION = File.read('VERSION').strip
RAILS_PATH = File.join('..', 'cveprovider')

Echoe.new('fidius-cvedb', CVE_VERSION) do |p|
  p.summary     = 'Foo'
  p.description = 'Bar'
  p.url         = 'http://fidius.me'
  p.author      = 'FIDIUS'
  p.email       = 'grp-fidius@tzi.org'
  p.runtime_dependencies = ['rails']
  p.development_dependencies = ['rake-hooks', 'echoe']
end

before :build do
  copy_files File.join('app', 'models')
  copy_files 'cveparser'
  copy_files File.join('lib', 'tasks')
  copy_files File.join('db', 'migrate')
end

after :package do
  version_increment
end

def version_increment
  File.open('VERSION', 'w') do |f|
    f.write CVE_VERSION.split('.').tap {|v| v[2].to_i + 1 }.join('.')
  end
end

def copy_files path
  FileUtils.cp_r(
    File.expand_path(File.join(RAILS_PATH, path)),
    File.expand_path(File.dirname(__FILE__))
  )
end
