require 'echoe'
require 'rake/hooks'
require 'rake/clean'

CLOBBER.include 'models'

VERSION = File.read('VERSION').strip
RAILS_PATH = File.join('..', 'cveprovider')

Echoe.new('FIDIUS-CVEinit', VERSION) do |p|
  p.summary     = 'Foo'
  p.description = 'Bar'
  p.url         = 'http://fidius.me'
  p.author      = 'FIDIUS'
  p.email       = 'grp-fidius@tzi.org'
  p.runtime_dependencies = ['rails']
  p.development_dependencies = ['rake-hooks', 'echoe']
end

before :build do
  copy_files
end

after :package do
  version_increment
end

def version_increment
  File.open('VERSION', 'w') do |f|
    f.write VERSION.split('.').tap {|v| v[2].to_i + 1 }.join('.')
  end
end

def copy_files
  FileUtils.cp_r(
    File.expand_path(File.join(RAILS_PATH, 'app', 'models')),
    File.expand_path(File.dirname(__FILE__))
  )
end
